create schema if not exists ecobee;
revoke all on schema ecobee from public, anon, authenticated;

create table if not exists ecobee.kv_store (
  scope text not null check (scope in ('private','shared')),
  key text not null,
  value text not null,
  updated_at bigint not null,
  primary key (scope,key)
);
create table if not exists ecobee.users (
  id bigint generated by default as identity primary key,
  phone text unique not null,
  name text not null,
  farm text not null,
  password_hash text not null,
  created_at bigint not null
);
create table if not exists ecobee.sessions (
  token text primary key,
  user_id bigint not null references ecobee.users(id) on delete cascade,
  expires_at bigint not null
);
create table if not exists ecobee.hives (
  id text primary key,
  user_id bigint references ecobee.users(id) on delete cascade,
  admin_id bigint,
  name text not null,
  species text not null,
  lat double precision not null,
  lng double precision not null,
  radius_km double precision not null,
  note text not null default '',
  is_public integer not null default 0 check (is_public in (0,1)),
  created_at bigint not null
);
create table if not exists ecobee.plants (
  id text primary key,
  user_id bigint references ecobee.users(id) on delete cascade,
  admin_id bigint,
  plant_type text not null,
  variety text not null default '',
  months text not null,
  geometry text not null,
  area_rai double precision,
  tree_count integer,
  bloom_status text not null default 'unknown',
  pesticide_use text not null default 'unknown',
  observed_at bigint,
  note text not null default '',
  created_at bigint not null
);
create table if not exists ecobee.plant_species (
  code text primary key,
  thai_name text not null,
  common_name text not null default '',
  scientific_name text not null default '',
  category text not null default 'other',
  resource_type text not null default 'unknown' check(resource_type in ('unknown','nectar','pollen','both')),
  nectar_score double precision check(nectar_score between 0 and 5),
  pollen_score double precision check(pollen_score between 0 and 5),
  nectar_amount double precision check(nectar_amount >= 0),
  nectar_unit text not null default '',
  sugar_brix double precision check(sugar_brix between 0 and 100),
  flowering_months text not null default '[]',
  source_title text not null default '',
  source_url text not null default '',
  confidence text not null default 'unverified' check(confidence in ('unverified','low','medium','high')),
  status text not null default 'draft' check(status in ('draft','approved','archived')),
  created_by bigint,
  created_at bigint not null,
  updated_at bigint not null
);
create table if not exists ecobee.risk_zones (
  id text primary key,
  user_id bigint references ecobee.users(id) on delete cascade,
  admin_id bigint,
  name text not null,
  status text not null check(status in ('safe','danger')),
  geometry text not null,
  note text not null default '',
  created_at bigint not null
);
create table if not exists ecobee.farm_boundaries (
  id text primary key,
  user_id bigint not null references ecobee.users(id) on delete cascade,
  name text not null,
  geometry text not null,
  target_species text not null,
  min_spacing_km double precision not null default 0.5 check(min_spacing_km between 0.1 and 20),
  created_at bigint not null
);
create table if not exists ecobee.movements (
  id text primary key,
  hive_id text not null references ecobee.hives(id) on delete cascade,
  from_lat double precision,
  from_lng double precision,
  to_lat double precision not null,
  to_lng double precision not null,
  reason text not null default '',
  checked_in_at bigint not null
);
create table if not exists ecobee.harvest_batches (
  id text primary key,
  hive_id text not null references ecobee.hives(id) on delete cascade,
  batch_code text unique not null,
  product text not null,
  harvested_at bigint not null,
  quantity_kg double precision not null check (quantity_kg > 0),
  metadata text not null default '{}'
);
create table if not exists ecobee.org_admins (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text not null,
  password_hash text not null,
  created_at bigint not null
);
create table if not exists ecobee.org_sessions (
  token text primary key,
  admin_id bigint not null references ecobee.org_admins(id) on delete cascade,
  expires_at bigint not null
);
create table if not exists ecobee.user_verifications (
  user_id bigint primary key references ecobee.users(id) on delete cascade,
  safety integer not null default 0 check (safety in (0,1)),
  standard integer not null default 0 check (standard in (0,1)),
  updated_at bigint not null
);
create table if not exists ecobee.org_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id bigint not null,
  action text not null,
  target text not null,
  details text not null default '{}',
  created_at bigint not null
);
create table if not exists ecobee.password_reset_requests (
  id text primary key,
  user_id bigint not null references ecobee.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at bigint not null,
  resolved_at bigint,
  admin_id bigint references ecobee.org_admins(id) on delete set null
);

alter table ecobee.hives add column if not exists admin_id bigint;
alter table ecobee.hives add column if not exists is_public integer not null default 0;
alter table ecobee.hives alter column user_id drop not null;
alter table ecobee.plants add column if not exists admin_id bigint;
alter table ecobee.plants alter column user_id drop not null;
alter table ecobee.plants add column if not exists area_rai double precision;
alter table ecobee.plants add column if not exists tree_count integer;
alter table ecobee.plants add column if not exists bloom_status text not null default 'unknown';
alter table ecobee.plants add column if not exists pesticide_use text not null default 'unknown';
alter table ecobee.plants add column if not exists observed_at bigint;
alter table ecobee.plants add column if not exists note text not null default '';
alter table ecobee.risk_zones add column if not exists admin_id bigint;
alter table ecobee.risk_zones alter column user_id drop not null;

create index if not exists sessions_user_id_idx on ecobee.sessions(user_id);
create index if not exists sessions_expires_at_idx on ecobee.sessions(expires_at);
create index if not exists hives_user_id_idx on ecobee.hives(user_id);
create index if not exists plants_user_id_idx on ecobee.plants(user_id);
create index if not exists plant_species_status_idx on ecobee.plant_species(status);
create index if not exists risk_zones_user_id_idx on ecobee.risk_zones(user_id);
create index if not exists farm_boundaries_user_id_idx on ecobee.farm_boundaries(user_id);
create index if not exists movements_hive_id_idx on ecobee.movements(hive_id);
create index if not exists harvest_batches_hive_id_idx on ecobee.harvest_batches(hive_id);
create index if not exists org_sessions_admin_id_idx on ecobee.org_sessions(admin_id);
create index if not exists org_sessions_expires_at_idx on ecobee.org_sessions(expires_at);
create index if not exists org_audit_logs_admin_id_idx on ecobee.org_audit_logs(admin_id);
create index if not exists password_reset_requests_user_id_idx on ecobee.password_reset_requests(user_id);
create index if not exists password_reset_requests_status_idx on ecobee.password_reset_requests(status);

alter table ecobee.kv_store enable row level security;
alter table ecobee.users enable row level security;
alter table ecobee.sessions enable row level security;
alter table ecobee.hives enable row level security;
alter table ecobee.plants enable row level security;
alter table ecobee.plant_species enable row level security;
alter table ecobee.risk_zones enable row level security;
alter table ecobee.farm_boundaries enable row level security;
alter table ecobee.movements enable row level security;
alter table ecobee.harvest_batches enable row level security;
alter table ecobee.org_admins enable row level security;
alter table ecobee.org_sessions enable row level security;
alter table ecobee.user_verifications enable row level security;
alter table ecobee.org_audit_logs enable row level security;
alter table ecobee.password_reset_requests enable row level security;

revoke all on all tables in schema ecobee from public, anon, authenticated;
revoke all on all sequences in schema ecobee from public, anon, authenticated;
