create schema if not exists ecobee;
revoke all on schema ecobee from public, anon, authenticated;

create table if not exists ecobee.kv_store (
  scope text not null check (scope in ('private','shared')),
  key text not null,
  value text not null,
  updated_at bigint not null,
  primary key (scope,key)
);
create table if not exists ecobee.users (
  id bigint generated by default as identity primary key,
  phone text unique not null,
  name text not null,
  farm text not null,
  password_hash text not null,
  created_at bigint not null
);
create table if not exists ecobee.sessions (
  token text primary key,
  user_id bigint not null references ecobee.users(id) on delete cascade,
  expires_at bigint not null
);
create table if not exists ecobee.hives (
  id text primary key,
  user_id bigint not null references ecobee.users(id) on delete cascade,
  name text not null,
  species text not null,
  lat double precision not null,
  lng double precision not null,
  radius_km double precision not null,
  note text not null default '',
  created_at bigint not null
);
create table if not exists ecobee.plants (
  id text primary key,
  user_id bigint not null references ecobee.users(id) on delete cascade,
  plant_type text not null,
  variety text not null default '',
  months text not null,
  geometry text not null,
  created_at bigint not null
);
create table if not exists ecobee.risk_zones (
  id text primary key,
  user_id bigint not null references ecobee.users(id) on delete cascade,
  name text not null,
  status text not null check(status in ('safe','danger')),
  geometry text not null,
  note text not null default '',
  created_at bigint not null
);
create table if not exists ecobee.movements (
  id text primary key,
  hive_id text not null references ecobee.hives(id) on delete cascade,
  from_lat double precision,
  from_lng double precision,
  to_lat double precision not null,
  to_lng double precision not null,
  reason text not null default '',
  checked_in_at bigint not null
);
create table if not exists ecobee.harvest_batches (
  id text primary key,
  hive_id text not null references ecobee.hives(id) on delete cascade,
  batch_code text unique not null,
  product text not null,
  harvested_at bigint not null,
  quantity_kg double precision not null check (quantity_kg > 0),
  metadata text not null default '{}'
);
create table if not exists ecobee.org_admins (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text not null,
  password_hash text not null,
  created_at bigint not null
);
create table if not exists ecobee.org_sessions (
  token text primary key,
  admin_id bigint not null references ecobee.org_admins(id) on delete cascade,
  expires_at bigint not null
);
create table if not exists ecobee.user_verifications (
  user_id bigint primary key references ecobee.users(id) on delete cascade,
  safety integer not null default 0 check (safety in (0,1)),
  standard integer not null default 0 check (standard in (0,1)),
  updated_at bigint not null
);
create table if not exists ecobee.org_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id bigint not null,
  action text not null,
  target text not null,
  details text not null default '{}',
  created_at bigint not null
);

create index if not exists sessions_user_id_idx on ecobee.sessions(user_id);
create index if not exists sessions_expires_at_idx on ecobee.sessions(expires_at);
create index if not exists hives_user_id_idx on ecobee.hives(user_id);
create index if not exists plants_user_id_idx on ecobee.plants(user_id);
create index if not exists risk_zones_user_id_idx on ecobee.risk_zones(user_id);
create index if not exists movements_hive_id_idx on ecobee.movements(hive_id);
create index if not exists harvest_batches_hive_id_idx on ecobee.harvest_batches(hive_id);
create index if not exists org_sessions_admin_id_idx on ecobee.org_sessions(admin_id);
create index if not exists org_sessions_expires_at_idx on ecobee.org_sessions(expires_at);
create index if not exists org_audit_logs_admin_id_idx on ecobee.org_audit_logs(admin_id);

alter table ecobee.kv_store enable row level security;
alter table ecobee.users enable row level security;
alter table ecobee.sessions enable row level security;
alter table ecobee.hives enable row level security;
alter table ecobee.plants enable row level security;
alter table ecobee.risk_zones enable row level security;
alter table ecobee.movements enable row level security;
alter table ecobee.harvest_batches enable row level security;
alter table ecobee.org_admins enable row level security;
alter table ecobee.org_sessions enable row level security;
alter table ecobee.user_verifications enable row level security;
alter table ecobee.org_audit_logs enable row level security;

revoke all on all tables in schema ecobee from public, anon, authenticated;
revoke all on all sequences in schema ecobee from public, anon, authenticated;
